### ISSUE TITLE
long delay during babel transpilation

### ISSUE THREAD

**Issue by jamesdixon** [danlynn/ember-cli#3]
Hi, first off, thanks for you work on this project. It's been immensely helpful!

I was able to get things setup and working properly, but when I initially start the container and it gets to the part where you see `Serving on http://localhost:4200`, there's a **significant** delay (on the order of 10s of minutes) between that message and when you see the output where Ember CLI displays how long it takes to compile everything. Have you run into this? I've tried using both the standard docker-machine setup as well as docker for mac with the same result.

**Comment by danlynn** [comment]
That really is odd.  I've never ran into that on any docker related container.  It will take longer to build larger projects.  But, you would have to have some really, really large project to take that long to build.

Switching your Mac and docker machine over to use NFS instead of shared folders (especially in VirtualBox) will yield a dramatic performance boost (like 5x faster).

Here's a gist I worked up a while back that shows how to manually switch over to using NFS instead of shared folders:
    https://gist.github.com/danlynn/685873d328aef7df115a https://gist.github.com/danlynn/685873d328aef7df115a

Good luck!

**Comment by jamesdixon** [comment]
Thanks for the quick reply!

I actually found some documentation on the Docker site that specifically calls out Ember as problematic due to issues with I/O performance on mounted volumes: https://docs.docker.com/docker-for-mac/troubleshoot/#/known-issues

**Comment by danlynn** [comment]
I have a tool I've been developing called docker-dev which is designed to handle development containers.  It makes containers look local - like typing 'ember init' or 'npm -v' in your host machine's project dir tree will actually execute within the container rather than local.  It also does magic for forwarding ssh agent interactions so that your mac keychain is used for ssh auth instead of having to copy your keys into the container.  One of the nicest features is that it runs watchman locally on your host then whenever you modify any files locally, it touches the files within the container triggering the watchman that is running within the container to pick up the changes immediately.  This makes it so that you don't have to turn polling on for the ember server running inside the container preventing lots of directory scanning going across the slow shared folder connection back to the host.

**Comment by jamesdixon** [comment]
@danlynn that sounds like a dream! When can I try it? 😄

**Comment by Gowiem** [comment]
@jamesdixon I'm running into this I believe as I've never seen my build step finish. Did you ever find a solution? Or @danlynn Did you ever complete your `docker-dev` library because that does sound interesting!

**Comment by danlynn** [comment]
I got the project working well on some projects.  But, I haven’t really pursued it further since switching to Docker for Mac.  The Docker for Mac helped alleviate some of the issues of working with docker-machine.  I’m not really sure if the additional features of my docker-dev would justify its usage for most people.  I’m thinking about breaking out its features into one-off smaller dev tools.

At any rate, the Babel transpiler is made up of like 70,000 files (depending on the options used).  This is quite a load on hypervisor shared folders or NFS shares.  You may try specifying Babel to be installed with the -g option so that it is all in the container and doesn’t have to access a large portion of this 70,000 files when transpiling.  Additionally, to save space and install time, you could specify that your node global install dir is a regular docker volume.  This means that a single dir in the docker host inside the hypervisor would be reserved for all containers to share the -g global node modules.

**Comment by Gowiem** [comment]
Cool. You're right, around 50% of the time is taken up by Babel: 
```
ember_1   | Build successful (301019ms) – Serving on http://localhost:8080/
ember_1   |
ember_1   |
ember_1   |
ember_1   | Slowest Nodes (totalTime => 5% )              | Total (avg)
ember_1   | ----------------------------------------------+---------------------
ember_1   | Babel (36)                                    | 157059ms (4362 ms)
ember_1   | EslintValidationFilter (3)                    | 83494ms (27831 ms)
ember_1   | Concat (6)                                    | 20891ms (3481 ms)
```

You mentioned a couple options... mind if I ask how I should go about doing those? I'm a bit of a Docker/compose noob. Not sure how I should go about making my node_modules global. Thanks!
