### ISSUE TITLE
Since Ember CLI 2.15 Chrome is default for CI

### ISSUE THREAD

**Issue by raido** [danlynn/ember-cli#8]
So this image should now include also Chrome installation next to PhantomJS to support both scenarios.

**Comment by danlynn** [comment]
It has always included phantomjs.  The difference is that it now uses the official phantomjs distribution rather than the prebuilt version found in the npm registry.  The ‘phantomjs’ npm package recently was asked to change its name to 'phantomjs-prebuilt’ since they were NOT connected with the official phantomjs organization.

**Comment by raido** [comment]
Well yes, I know. Please add also Google Chrome as Ember CLI 2.15 by default generates testem.js with headless chrome configuration.

**Comment by danlynn** [comment]
Alright.  Thanks for the heads up.  I totally missed the switch to headless chrome.  Also, it appears the livereload server switched to port 7020 - but, when you init a new project, it still uses 49153.  So, not sure what is going on there.

Also, I worked on getting headless chrome to work properly tonight and have ran into issues.  I might have to pull out some fancy shell tricks to get it working such that default ember-cli can invoke it without modification.

I pushed out a version without the working Chrome tonight.  However, if you want to play, you can try the following Dockerfile:


FROM node:6.11.2
MAINTAINER Dan Lynn <docker@danlynn.org>

# ember server on port 4200
# livereload server on port 49153 (changed in v2.11.1 from 49152)
EXPOSE 4200 49153
WORKDIR /myapp

# run ember server on container start
CMD ["ember", "server"]

# Install watchman build dependencies 
RUN \ 
   apt-get update -y &&\
   apt-get install -y python-dev
 
# install watchman
# Note: See the README.md to find out how to increase the
# fs.inotify.max_user_watches value so that watchman will 
# work better with ember projects.
RUN \
   git clone https://github.com/facebook/watchman.git &&\
   cd watchman &&\
   git checkout v4.7.0 &&\
   ./autogen.sh &&\
   ./configure &&\
   make &&\
   make install

# Install ember dev dependencies
RUN \
   npm install -g bower@1.8.0

# Install deps + add Chrome Stable
RUN apt-get update &&\
    apt-get install -y \
        apt-transport-https \
        gnupg \
        --no-install-recommends &&\
   curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - &&\
   echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list &&\
   apt-get update &&\
   apt-get install -y \
       google-chrome-stable \
       --no-install-recommends

# Install ember-cli
RUN \
   npm install -g ember-cli@2.15.0
If you launch into bash, you can run chrome with the —no-sandbox option and ignore the warning:

# google-chrome --no-sandbox ...

Without the —no-sandbox, it exits with an error.

I might not be able to get to this for a few days.  I have to prepare for the hurricane in Florida.

Good luck!

**Comment by raido** [comment]
Thanks! I'll try it out and if I find anything helpful I'll let you know.

**Comment by danlynn** [comment]
To clarify, if you add the —no-sandbox option to the testem.js config as follows then `ember test` will work:

/* eslint-env node */
module.exports = {
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  launch_in_ci: [
    'Chrome'
  ],
  launch_in_dev: [
    'Chrome'
  ],
  browser_args: {
    Chrome: [
      '--disable-gpu',
      '--headless',
      '--remote-debugging-port=9222',
      '--window-size=1440,900',
      '--no-sandbox'
    ]
  }
};
So, if you just need your tests to run, you can make this change to your project.

What I’m trying to do is make testem work with the default config and using some unixy tricks to make all executions of headless chrome in the docker container use the —no-sandbox option by default.

**Comment by raido** [comment]
Maybe it is just some permission issue or need to create like separate user account for chrome only?

**Comment by raido** [comment]
I don not really like the no sandbox flag as it would be nice to keep it as close defaults as possible. I mean one would test app without the sandbox and in real life sandbox enabled environment the app fails is not a favorable use case.

**Comment by danlynn** [comment]
It’s a permissioning issue related to running within docker and root.  It would take more time to switch the image to run as a non-root user and test all the issues associated with the various use cases.

I fixed the issue regarding making default apps with default configs work.  It will now run the tests in headless chrome (with the —no-sandbox option) without any changes to testem.js config file.  Also, I’m including both phantomjs and headless chrome in the image so that older projects with existing test configs will still work.

I’ll be pushing this out to docker hub later tonight.

**Comment by danlynn** [comment]
If I can find a way to avoid the —no-sandbox then I will.  But, I’m not overly concerned due to the nature of it only being used for tests in a development environment.  Also, the docker container runs as root by default and relies on containment to sandbox the whole process.

**Comment by raido** [comment]
I updated one of my projects to use latest image and switched to Chrome - everything went seamlessly. Thank you!
